version: "3.1"
services:
  database-mariadb:
    image: mariadb:10.7.1
    environment:
      - MARIADB_ROOT_PASSWORD=password
    volumes:
      - ../data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - "database-mariadb:db"
    ports:
      - "8081:80"
